services:

  postgres_client:
    image: postgres
    container_name: postgres-client-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: d3Client
    volumes:
      - postgres_client_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: always

  flyway_client:
    image: flyway/flyway
    container_name: flyway-client-container
    command: -url=jdbc:postgresql://postgres_client:5432/d3Client -user=user -password=12345678 migrate
    volumes:
      - ../migrations/clients:/flyway/sql
    depends_on:
      - postgres_client

  client:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: client-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_client:5432/d3Client
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 12345678
    ports:
      - "8082:8080"
    depends_on:
      - postgres_client
      - flyway_client

volumes:
  postgres_client_data:
