version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: d3
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
