version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: d3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway
    container_name: flyway-container
    command: -url=jdbc:postgresql://postgres:5432/d3 -user=user -password=12345678 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - postgres

volumes:
  postgres_data:
