spring:
  application:
    name: pedido
  datasource:
    url: jdbc:postgresql://localhost:5432/d3
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
server:
  port: 8083

custom:
  client-url: "http://localhost:8082"
  product-url: "http://localhost:8081"
