spring:
  application:
    name: pedido
  datasource:
    url: jdbc:postgresql://localhost:5432/d3?currentSchema=orders
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  graphql:
    cors:
      allowed-origin-patterns: http://localhost:8081,http://localhost:8082,http://localhost:8083
server:
  port: 8083
#  port: 8080

custom:
  client-url: "http://localhost:8082"
  product-url: "http://localhost:8081"
