spring:
  application:
    name: pedido
  datasource:
    url: jdbc:postgresql://localhost:5432/d3?currentSchema=orders
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

server:
  port: 8083
#  port: 8080


custom:
  client-url: "http://ec2-18-228-150-172.sa-east-1.compute.amazonaws.com:8080"
  external-client-url: "http://client:8080"
  external-product-url: "http://inventory:8080"
  product-url: "http://localhost:8081"

