spring:
  application:
    name: client
  datasource:
    url: jdbc:postgresql://localhost:5433/d3Client
    username: user
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
server:
  port: 8082
#  port: 8080

springdoc:
  paths-to-match: /ms/v1/client/**
  swagger-ui:
    use-root-path: true

